on:
  push:
    branches: main

jobs:
  update-report:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::googlesheets4
            any::gt
            any::tidyquant

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Render Quarto report
        run: quarto render report.qmd
        run: quarto render financial_analysis.qmd

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add report.html
          git add financial_analysis.html
          git commit -m 'Report updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

